CREATE TABLE Contact
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(40) NOT NULL,
    last_name    VARCHAR(40) NOT NULL,
    photo_url    VARCHAR,
    phone_number VARCHAR(20) NOT NULL
)

